In [1]:
import numpy as np

In [2]:
print('Enter length of vector')
n = input()
a = []
print('Enter Vector elements :')
for i in range(int(n)):    
    num = input()
    a.append(int(num))
x = np.array(a)   

Enter length of vector
5
Enter Vector elements :
2
3
1
4
5


In [3]:
x

array([2, 3, 1, 4, 5])

In [4]:
print('Enter number of columns to the output vector')
N = int(input())

Enter number of columns to the output vector
5


# increasing is false

In [5]:
np.vander(x,N)

array([[ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [  1,   1,   1,   1,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

# increasing is True

In [6]:
np.vander(x,N,True)

array([[  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   1,   1,   1,   1],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

# Function to find a moving average in an array over a window

In [30]:
def movingavg(x,size):
    avgs = []
    for i in range(len(x)-size+1):
        sum = 0
        for j in range(i,i+size):
            sum = sum + x[j]              
        avgs.append(sum/size)
    
    print ('length of moving average sequence array is ' + str(len(avgs)))
    print ('Moving average array :')
    print (avgs)      
    

In [31]:
print ('Enter length of array :')
length = int(input())
print ('Enter elements of an array')
x = []
for i in range(length):
    num1 = int(input())
    x.append(num1)
print('Enter window size')
size = int(input())
movingavg(x,size)

Enter length of array :
13
Enter elements of an array
3
5
7
2
8
10
11
65
72
81
99
100
150
Enter window size
3
length of moving average sequence array is 11
Moving average array :
[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
